Change version spec for `childprocess' dependency
  We still use old aruba versions (for example ~> 0.8), which have very
specific version requirement for childprocess gem:

ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies childprocess (~> 0.8) and childprocess (~> 0.5.6)
  Activated childprocess-0.5.6
  which does not match conflicting dependency (~> 0.8)

  Conflicting dependency chains:
    aruba (< 0.9, >= 0.8.1), 0.8.1 activated, depends on
    childprocess (~> 0.5.6), 0.5.6 activated

  versus:
    cucumber-sshd (= 2.0.0.pre), 2.0.0.pre activated, depends on
    childprocess (~> 0.8)